### ISSUE TITLE
Timeout for WinRM

### ISSUE THREAD

**Issue by bluesprucedan** [luciusbono/Packer-Windows10#22]
Ran the script overnight, and both vmware-iso and virtualbox-iso timed out waiting for WinRM.

**Comment by bluesprucedan** [comment]
@luciusbono The script can't read the product key from the autounattend.xml file.  I've tried 3 different autounattend.xml files and none of them will work.

**Comment by bluesprucedan** [comment]
@luciusbono Welp, now it still times now waiting for WinRM

**Comment by luciusbono** [comment]
Thanks for bringing this up, and sorry for the long delay (this is a side project for me). Turns out the Autounattend.xml file was totally borked, but it's all fixed up now.
