### ISSUE TITLE
Issue: Universal Windows Platform app icons show downloading icon

### ISSUE THREAD

**Issue by luciusbono** [luciusbono/Packer-Windows10#23]
It appears that the Windows Store isn't able to download all the UWP apps that ship with W10

![image](https://user-images.githubusercontent.com/5789441/44485402-48217680-a605-11e8-9899-152078d24abb.png)

**Comment by luciusbono** [comment]
Haven't found the full solution yet, but the following forces a re-download of all the UWP apps and "fixes" the problem: 

```powershell
$namespaceName = "root\cimv2\mdm\dmmap"
$className = "MDM_EnterpriseModernAppManagement_AppManagement01"
$methodName = "UpdateScanMethod"

$session = New-CimSession
$params = New-Object Microsoft.Management.Infrastructure.CimMethodParametersCollection


try
{
    $instance = Get-CimInstance -Namespace $namespaceName -ClassName $className
    $session.InvokeMethod($namespaceName, $instance, $methodName, $params)
}
catch [Exception]
{
    write-host $_ | out-string
}
```
Trouble is, it doesn't wait for the actual download / scan to complete before it returns a success code, so staging might be kind of wonky. The WMI object has an attribute called `LastScanError` that could be useful for staging, but I'm dubious about spamming the `UpdateScanMethod` method over and over again just to check to see if there are still updates. More to come.

**Comment by farag2** [comment]
Get-CimInstance -Namespace "Root\cimv2\mdm\dmmap" -ClassName "MDM_EnterpriseModernAppManagement_AppManagement01" | Invoke-CimMethod -MethodName UpdateScanMethod

**Comment by luciusbono** [comment]
This appears to be fixed (tested in Windows 10 2004)
