### ISSUE TITLE
Support HyperV Gen 1 VMs

### ISSUE THREAD

**Issue by luciusbono** [luciusbono/Packer-Windows10#32]
I need to start supporting HyperV, since running Docker on Windows is a pain if you've got another Hypervisor. 

Generation 2 VMs would require a separate autounattend.xml file, I _believe_, because they'd have to use UEFI and generation 2 VMs don't support virtual floppy disks, so a whole crazy dance where I'd have to build an ISO with the autounattend.xml file and the rest of the scripts in the build would have to happen. 

I also suspect that a Generation 2 VM might be worse for certain types of client testing, as it may "aware it's a VM" which could change how some software behaves. More research required.

**Comment by gildas** [comment]
Hey Lucius,
So for what it takes, I am almost done with Hyper-V support.

Generation 1, that is. Not sure a Generation 2 is worth the pain, actually.

The code is in my fork. I just need to run another test, maybe tomorrow (I am on JST).

**Comment by luciusbono** [comment]
Awesome! I'll pull down your code and test locally as well. That's exciting, this has been on my to-do list for ages.

**Comment by luciusbono** [comment]
Your HyperV config mostly works, although I get this: 

![image](https://user-images.githubusercontent.com/5789441/50367059-4a073200-0532-11e9-9922-7bbd15504472.png)

I wonder if this is something we'd solve for in the autounattend.xml. I'll dig in a bit!

EDIT: Ah, it's popping that up because the Virtual Switch is not connected to the internet!

**Comment by luciusbono** [comment]
Ah, realized this was my error. I specified a virtual switch name via the variable without realizing you had a default that maps to a virtual switch that appears to be pre-loaded in Windows. Rebuilding again with your defaults to verify!

**Comment by luciusbono** [comment]
Ah, realized this was my error. I specified a virtual switch name via the variable without realizing you had a default that maps to a virtual switch that appears to be pre-loaded in Windows. Rebuilding again with your defaults to verify!

**Comment by luciusbono** [comment]
Merged https://github.com/luciusbono/Packer-Windows10/pull/33 which integrates your fork into this project. HyperV support worked great, and once again I think you for your contribution! I preserved your commit history so you have commit credit for the changes and mentioned you in the README but let me know if you'd like credit anywhere else.

**Comment by gildas** [comment]
Oh cool, thanks. Good thing you did that test, that was the last one I had to do.

I will see if I can find some time to add kvm. Could be a bit longer as I am not at home next week and will not have easy access to my linux gear.

**Comment by gildas** [comment]
The README.md might require a bit more work as there are missing stuff for Hyper-V. Not big issues, mainly cosmetics.
